name: CD - Deploy Docker no Amazon ECR

on:
  push:
    branches:
      - master
      
permissions:
  id-token: write   # ‚Üê ESSENCIAL para OIDC
  contents: read    # ‚Üê Para ler o c√≥digo
  
jobs:
  deploy:
    name: Buildar e enviar imagem para o ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do reposit√≥rio
      uses: actions/checkout@v4

    - name: Configurar AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login no ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build da imagem Docker
      run: |
        docker build -t fcg-gamelibrary .

    - name: Tag para o ECR
      run: |
        # docker tag fcg-gamelibrary:latest ${{ secrets.ECR_REPOSITORY }}:latest
        docker tag fcg-gamelibrary:latest ${{ secrets.ECR_REPOSITORY }}:latest
    - name: Push no ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Configurar credenciais AWS via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::399668701651:role/GitHubActionsEKSRole
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHubActionsSession

    - name: Configurar o kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Obter credenciais do cluster EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Debug - Testar conex√£o EKS
      run: |
        echo "Testando conex√£o com o cluster..."
        kubectl cluster-info
        kubectl get nodes

    - name: Create or update Kubernetes secret for Game Library
      run: |
        kubectl create secret generic fcg-ms-gamelibrary-secret \
        --from-literal=ConnectionStrings__DefaultConnection="${{ secrets.GAMELIBRARY_DB_CONNECTION }}" \
        --from-literal=Elastic__Uri="${{ secrets.ELASTIC_URI }}" \
        --from-literal=Elastic__XApiKey="${{ secrets.ELASTIC_XAPIKEY }}" \
        --dry-run=client -o yaml | kubectl apply -f -

    - name: Aplicar Deployment no EKS
      run: |
        kubectl apply -f k8s/gamelibrary-deployment.yaml
        kubectl rollout status deployment/fcg-ms-gamelibrary --namespace default
    
    - name: Verificar deployment
      run: |
        kubectl get pods -l app=fcg-ms-gamelibrary
        kubectl get service fcg-ms-gamelibrary-service
        echo "üéâ GameLibrary LoadBalancer URL:"
        kubectl get service fcg-ms-gamelibrary-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

